name: build-on-push
on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Build prebuilds
        uses: ./.github/actions/build
        env:
          JOBS: 3
      - name: Upload prebuilds
        uses: actions/upload-artifact@v1
        with:
          name: prebuilds
          path: prebuilds

  build-other:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build-prebuild
        env:
          JOBS: 3
      - name: Upload prebuilds
        uses: actions/upload-artifact@v1
        with:
          name: prebuilds
          path: prebuilds

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: sudo apt-get -y install lcov
      - run: npm install
        env:
          JOBS: 3
          ZSTD_NAPI_ENABLE_GCOV: 1
      - run: npm run test-lcov
      - name: Combine coverage data
        run: |
          lcov -c -d . -o binding-lcov-raw.info --rc lcov_branch_coverage=1
          lcov -e binding-lcov-raw.info "$(pwd)/src/*" -o binding-lcov.info
          lcov -a binding-lcov.info -a coverage/lcov.info -o combined-lcov.info
      - name: Submit coverage data to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./combined-lcov.info
