name: build
on:
  push:
    branches:
      - update

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
        env:
          JOBS: 3
          ZSTD_NAPI_ENABLE_GCOV: 1
      - run: npm run test-coverage
      - name: Submit coverage data to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: ./node_modules/.bin/tsc
      - id: npm_pack
        name: Build npm package
        run: echo "::set-output name=package::$(npm pack)"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install clang-format
        run: |
          sudo apt-get -y update
          sudo apt-get -y install clang-format-9
      - run: npm ci --ignore-scripts
      - run: npm run lint
      - name: Check JS/TS is formatted with Prettier
        run: ./node_modules/.bin/prettier --check '**/*.{js,json,ts}'
      - name: Check C++ is formatted with clang-format
        run: |
          clang-format-9 -i src/*
          git diff --stat --exit-code src/
